name: macOS CI

on: [push, pull_request]

jobs:
  macos-build:
    runs-on: macos-13
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake .. \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_CXX_COMPILER=clang++ \
            -DTOY_BUILD_TEST=ON \
            -DTOY_BUILD_BENCHMARK=ON \
            -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cd build
          cmake --build . --parallel $(sysctl -n hw.logicalcpu)

      - name: Run Tests
        shell: bash
        run: |
          ./build/test/toy_test
          ./build/test/benchmark/toy_bench
