name: Windows CI (VS2022)

on: [push, pull_request]

jobs:
  windows-msvc:
    name: Windows (MSVC)
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # CMake 工具链配置
      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake .. `
            -G "Visual Studio 17 2022" `
            -A x64 `
            -DTOY_BUILD_TEST=ON `
            -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cd build
          cmake --build . --config Release --parallel 4

      - name: Run Tests
        shell: bash
        run: |
          ./build/test/Release/toy_test.exe
